apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-test
  labels:
    name: argocd-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: argocd-test
  template:
    metadata:
      labels:
        app: argocd-test
    spec:
      containers:
        - name: argocd-test
          image: mehrenre/argocd-test:1.0.1
